### ISSUE TITLE
No translation happens

### ISSUE THREAD

**Issue by LichtiMi** [Rapha149/ulauncher-deepl#1]
Hi, 

when I enter 'tr' followed by a text I want to be translated I am asked for auto-detection or the language from which I want to translate and after that a list of target languages is offered but independend of the selected target language no translation happens.
Can I provide any additional information to help searching for a solution?

CU
Michi

**Comment by Rapha149** [comment]
Yes, I have experienced that myself lately, but I didn't have the time to take a look at it. The translation using the last target languages still works though.
I will take a look at it today.

**Comment by Rapha149** [comment]
Fixed it in the newest commit, I somehow deleted an important line while fixing something else in the past and didn't notice it.
Thanks for reporting!

**Comment by LichtiMi** [comment]
Thanks a lot for that quick reaction!
At least it was reproduceable and as it seems easy to find. :)
It works now!
