### ISSUE TITLE
How would I select a target language that is not displayed?

### ISSUE THREAD

**Issue by deedeedev** [Rapha149/ulauncher-deepl#2]
At any point in time Ulauncher shows only a limited number of results. How can I select languages other than the ones on top of the list? For example "Italian".

How to reproduce:
1. Invoke Ulauncher
2. Write "tr some text to translate"
3. Press Alt+Enter for auto detecting the source language
4. A list of target languages is presented, but not all are visible/selectable

**Comment by Rapha149** [comment]
Oh yeah I didn't think about that. I will make a page system then.
Don't know exactly when I'll have time, but I should get it done by Friday I think.

**Comment by Rapha149** [comment]
@deedeedev I'm sorry that it took a little longer but I had many things going on and so I forgot about it for a few days. But now the paging system is finished!
Thanks for bringing the problem to my attention :slightly_smiling_face:
