### ISSUE TITLE
Default language, or language from input

### ISSUE THREAD

**Issue by Paul-Aime** [Rapha149/ulauncher-deepl#3]
Thanks for the extension.

Would it be possible to set a default target language?
And / or to choose it by typing it instead of having to go through the list of choice and click?

`tr from_lang:to_lang some text`

In a similar manner than what is done for Google Translate in https://github.com/manahter/ulauncher-translate:

**Comment by Rapha149** [comment]
Thanks for the suggestions!

For the default target language:
I could imagine adding another keyword and a setting for a default target language. That setting would only apply when using the new keyword. Would you want to be able to select a source language then? Or should I make another setting for a source language / auto detect? Or should the extension when using the new keyword always detect the language?

For your other suggestion:
I like that! Don't know why I didn't think of it before.

**Comment by Paul-Aime** [comment]
I kind of like the way https://github.com/manahter/ulauncher-translate handle this.
But I guess interactive selection via menus should also be kept.

So to combine both I would see something as follows:

**In the extensions settings:**

Input language:

- ( ) "interactive"
- ( ) "automatic"
- ( ) "custom" (enter the 2 letter language indicator)

Output language:

- ( ) "interactive"
- ( ) "automatic" (not sure it is relevant)
- ( ) "custom" (enter the 2 letter language indicator)

**Usage:**

The general usage would be:

`tr from:to Something to translate`

If the `from:to` part is missing, then they are picked up from the settings above.
Thus, by making "interactive" the default for "Input language" and for "Output language", you keep the current behavior by default, and no need for a new keyword.

Also, it should be possible for only a single part of the `from:to` to be there, but the `:` should be there to detect it is the argument and not the text to translate.

This is because, imho, the most common use case would be to have the following settings:

- Input language: "automatic"
- Output language: "xx" (my native language)

That way I think it makes for the quickest usage for multiple cases:

- `tr Whatever language is detected`: I get a translation into my native language;
- `tr :xx Whatever language is detected`: I get a translation into whatever language I want it;
- `tr xx:xx It was an ill detected input language`: If ever the input language detection failed.

Additionnaly, maybe `auto` and `interactive` should be valid keywords for the `from:to` syntax.
This is because if I don't know the 2 letters indicator for a target language (but I don't have "interactive" as my setting for "Output language") I could then still do:

`tr :interactive The text I want to translate in a language I don't know the indicator`

Also `interactive` could be named otherwise, like `select` for example.

**Comment by Rapha149** [comment]
Good idea!
I personally coded it the way it is now because I mostly need my extension in school. And cause I have English and Spanisch lessons I need both languages. Also I often have to translate in both directions (e.g. from English to German and from German to English). But if it's customizable in the settings there would be no problem for either use cases to exist.

I don't know how long exactly it will take me to implement this but I don't really have anything else to do today, so it could be that I get it done by today.

**Comment by Paul-Aime** [comment]
Thanks for the reactivity!

I do myself also often translate in 2 ways.
But let's say it is `de:en` 60% of the the time and `en:de` 40% of the time, then I would have `en` as output language in the settings (and `auto` as input language).
That way it would be the bare `tr etwas text` 60% of the time and `tr :de some text` 40% of the time.

If you want to push it further you can even allow for an ordered list of output languages ("Output language": `en;de`).
The translation would happen into the first language of that list that is not also the (detected) input language.
That way it would be the bare `tr etwas text` and `tr some text` 100% of the time!
But I don't know if it possible since maybe you can't auto detect the input language before translation.

**Comment by Rapha149** [comment]
No that's not possible without another API that could detect languages.

**Comment by Rapha149** [comment]
Update is online. I also included a description of the preferences in the readme. Tell me what you think!

**Comment by Paul-Aime** [comment]
It was quick! And perfect I think, thank you!

**Comment by Rapha149** [comment]
You're welcome!
